### ISSUE TITLE
how to add class,interface and enum in leadbolt codes

### ISSUE THREAD

**Issue by palashmandokhot** [danielstjules/buddy.js#22]
how to add class,interface and enum in leadbolt codes

**Comment by danielstjules** [comment]
Hi! Can you elaborate? Not sure I understand the question :)

**Comment by palashmandokhot** [comment]
hello,
i add some codes in my android studio so its shows error class,interface and enum so how to solve this problem.

**Comment by palashmandokhot** [comment]
hello,
i add some codes in my android studio so its shows error class,interface
and enum so how to solve this problem.

**Comment by danielstjules** [comment]
Sorry, not sure I can help! I don't have any experience with android studio.

**Comment by palashmandokhot** [comment]
if you know about codings so can you tell me where add class,interface and
enum in some codes.

**Comment by palashmandokhot** [comment]
if you know about codings so can you tell me where add class,interface and
enum in some codes.

**Comment by danielstjules** [comment]
Sorry, if you're looking for help learning Java (this is a JavaScript project) I'd suggest posting on StackOverflow or some other forum.
